# Generated by Django 4.2.7 on 2023-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_nombre_del_curso_cursos_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('numero_de_contacto', models.CharField(max_length=50, null=True)),
                ('adeuda_cuota', models.BooleanField(default=False, verbose_name='Adeuda_cuota')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='alumnos',
            field=models.ManyToManyField(to='cursos.alumnos'),
        ),
    ]
