# Generated by Django 4.2.3 on 2023-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_cursos_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='alumnos',
            field=models.ManyToManyField(to='cursos.alumnos'),
        ),
    ]
