# Generated by Django 4.2.3 on 2023-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_cursos_alumnos_alumnos_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='cursos',
        ),
        migrations.AddField(
            model_name='cursos',
            name='alumnos',
            field=models.ManyToManyField(related_name='cursos', to='cursos.alumnos'),
        ),
    ]
