# Generated by Django 4.2.3 on 2023-12-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='asistio',
            new_name='presente',
        ),
    ]
