# Generated by Django 4.2.3 on 2023-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_rename_asistio_asistencia_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(),
        ),
    ]
