# Generated by Django 4.2.3 on 2023-12-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_asistencia_presente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
    ]
